### ISSUE TITLE
How can I hide the calendar symbol on date added gallery

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9159]
![Screenshot - 2024-06-25T170542 426](https://github.com/WWBN/AVideo/assets/39392449/1f70ed73-5a53-474c-88fb-2043d74720fa)

**Comment by DanielnetoDotCom** [comment]
you can try to add a custom CSS to hide it.

**Comment by JoshWho** [comment]
That is what I was hoping but I do not see a css displaying it to modify.

**Comment by DanielnetoDotCom** [comment]
What is the URL for this site?

**Comment by JoshWho** [comment]
It is https://ftjmedia.com/

**Comment by DanielnetoDotCom** [comment]
# hide all title

```css
h3.galleryTitle {
   display: none;
}

```

# hide icon only

```css
h3.galleryTitle > a > i{
   display: none;
}
```
