### ISSUE TITLE
Chat 2 needs to make the bubbles only dark background and use white text in Dark theme

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9476]
![02f4eb80-d7e5-4cad-a815-8cc434b1b6ee](https://github.com/user-attachments/assets/712ead64-c2c1-4710-a174-922d6087099e)

**Comment by JoshWho** [comment]
Any way to make it work like the other chats on other streams so the overlay is not using any white for background but only for font?

**Comment by JoshWho** [comment]
eg 
![th (7)](https://github.com/user-attachments/assets/d6f735ba-53d6-4b7c-964c-9ce48d313005)

**Comment by DanielnetoDotCom** [comment]
What do you mean?

**Comment by JoshWho** [comment]
Exactly like the photo see how dark mode bubble is dark with white text in the picture?

**Comment by DanielnetoDotCom** [comment]
I see, do you mean the bubble colors right?

**Comment by DanielnetoDotCom** [comment]
try to add this custom cdd


`````css

/* Darker background for them-bubble */
.them-bubble {
    background-color: #2c3e50; /* Dark slate */
    color: #ecf0f1; /* Light text for readability */
    border-radius: 10px;
    padding: 10px;
    margin-bottom: 10px;
}

/* Darker background for me-bubble */
.me-bubble {
    background-color: #34495e; /* Darker blue-grey */
    color: #ecf0f1; /* Light text for readability */
    border-radius: 10px;
    padding: 10px;
    margin-bottom: 10px;
}

/* Ensure the message text is readable */
.them-bubble .message,
.me-bubble .message {
    color: #ecf0f1; /* Light text for readability */
}

/* Ensure the messageFooter text is readable */
.them-bubble .messageFooter,
.me-bubble .messageFooter {
    color: #bdc3c7; /* Slightly lighter grey for footer text */
    font-size: 0.85em;
    margin-top: 5px;
}

``````
